### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by amycatgirl** [upryzing/crescent#7]
It would be nice to plan out a roadmap

**Comment by amycatgirl** [comment]
Alright, here is a bunch of stuff I have planned for Crescent:

- [ ] Better internal API Client
- [ ] Attachments (Video, Images, Audio, Files)
- [ ] Reactions (Limited to unicode emoji)
- [ ] Voice Messages
- [ ] Colour themes (Dark, Light and Material You)
- [ ] Pinned messages
- [ ] Unreads
- [ ] Mention autocomplete 
- [ ] Save token to system keychain (currently it's saved to preferencestore, don't ask why)
- [ ] Message actions (Remove, report, edit, reply)
- [ ] Small markdown range (similar to revoltmini)

If you want any new stuff, lmk

**Comment by retcinder** [comment]
Would it be appropriate to put this under "Needs discussion" on the issue tracker?

**Comment by amycatgirl** [comment]
I don't think the roadmap could be classified under that category

i guess if different issues for each task are made then sure????
